variable "region" {}
variable "vpc_name" {}
variable "vpc_cidr" {}
variable "igw_name" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "ecs_task_execution_name" {}
variable "alb_sg_name" {}
variable "ecs_sg_name" {}
variable "alb_name" {}
variable "tg_name" {}
variable "certificate_arn" {}
variable "ecr_name" {}
variable "ecs_cluster_name" {}
variable "ecs_task_family" {}
variable "ecs_container_name" {}
variable "ecs_service_name" {}
variable "log_group_name" {}
variable "retention_in_days" {}
